# Generated by Django 5.1.4 on 2025-01-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0059_alter_blogcomments_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(max_length=300),
        ),
    ]
